spring.application.name=peliculas-service
server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/bd_peliculas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none